<?php
use Yotpo\Core\Block\Adminhtml\System\Config\LaunchYotpoButton;
use Magento\Framework\Escaper;

/**
 * @var $block LaunchYotpoButton
 * @var Escaper $escaper
 */
$escaper = $escaper ?? $block;
?>
<?php if (!$block->isStoreScope()): ?>
    <p class="note">
        <?= $escaper->escapeHtml(__('Yotpo can only be connected, enabled, or disabled via the Store View menu.'))?><br>
        <?= $escaper->escapeHtml(__('To connect your App Key and API secret, first select the relevant Store View.')) ?>
    </p>
    <p></p>
    <style>
        tr#row_yotpo_settings_active,tr#row_yotpo_settings_app_key,tr#row_yotpo_settings_secret{display:none!important;}
    </style>
<?php endif; ?>
<p class="note">
    <?= $escaper->escapeHtml(__('Need help?')) ?>
    <a href="https://docs.magento.com/m2/ee/user_guide/marketing/yotpo-connect.html"
       target="_blank"
       title="<?= $escaper->escapeHtmlAttr(__('Setup Guide')) ?>">
        <?= $escaper->escapeHtml(__('Setup Guide')) ?>
    </a>
</p>
